version: '3'
services:
  ros2_humble:
    image: ros2_humble   # Name of the Docker image
    privileged: true
    build: .             # Context for building the image (current directory)
    volumes:
      - ./src:/ros2_ws/src  # Mount host directory to container directory
      - /tmp/.X11-unix:/tmp/.X11-unix:rw  # Mount X11 socket for display forwarding
      - $HOME/.Xauthority:/root/.Xauthority:ro
    environment:
      - DISPLAY=${DISPLAY}  # Forward the DISPLAY environment variable
      - QT_X11_NO_MITSHM=1  # Necessary for Qt applications to run in the container
      - LIBGL_ALWAYS_SOFTWARE=1  # Force software rendering
      - XAUTHORITY=$XAUTH
    stdin_open: true     # Keep STDIN open even if not attached
    tty: true            # Allocate a pseudo-TTY
    network_mode: host   # Use the host network
